# Generated by Django 4.0.4 on 2022-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.AddField(
            model_name='profile',
            name='niveaux',
            field=models.CharField(blank=True, choices=[('SEC', 'Seconde'), ('PRE', 'Première'), ('TER', 'Terminale'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('OTH', 'Autre')], max_length=4),
        ),
    ]
