# Generated by Django 4.0.4 on 2023-08-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_profession_profile_niveaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profi_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
