# Generated by Django 4.0.4 on 2023-08-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_profi_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profi_pic',
            new_name='profile_pic',
        ),
    ]
