# Generated by Django 4.0.4 on 2022-05-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlePost', models.CharField(max_length=50)),
                ('contentPost', models.TextField()),
                ('authorPost', models.CharField(max_length=100)),
                ('datePost', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now_add=True)),
                ('slugPost', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentComment', models.TextField(max_length=1000)),
                ('commentedByUser', models.CharField(max_length=100)),
                ('commentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumpost')),
            ],
        ),
    ]
