# Generated by Django 4.0.4 on 2022-12-31 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_post_alter_postcomment_commentpost_delete_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('reactionDate', models.DateTimeField(auto_now_add=True)),
                ('reactedPost', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='forum.post')),
                ('reactionAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
