# Generated by Django 4.0.4 on 2023-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentPostHTML',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='contentCommentHTML',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
